# Create the ECmean4 development environment:
# mamba env create -f dev-environment.yml 
# or 
# conda env create -f dev-environment.yml

name : dev-ecmean
channels:
  - conda-forge
dependencies:
  - python>=3.9
  - libnetcdf
  - xesmf
  - dask
  - eccodes
  - esmpy
  - cdo
  - ncview
  - ipykernel
  - flake8
  - autopep8
  - pip
  - pip:
    - -e .[all]

