# Create the ECmean4 environment:
# mamba env create -f environment.yml 
# or 
# conda env create -f environment.yml

name : ecmean
channels:
  - conda-forge
dependencies:
  - python>3.9
  - xesmf
  - eccodes
  - pip
  - pip:
    - -e .

